# Generated by Django 3.1.4 on 2021-01-29 18:21

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('description', models.TextField(max_length=150, verbose_name='Описание')),
                ('avatar', models.ImageField(upload_to='image/', verbose_name='Аватарка')),
                ('link_site', models.URLField(verbose_name='URL сайта')),
                ('link_github', models.URLField(verbose_name='URL GitHub')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'автора',
                'verbose_name_plural': 'автор',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, max_length=250, unique='category')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
            },
            managers=[
                ('category_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='date_published')),
                ('post_prevew', ckeditor_uploader.fields.RichTextUploadingField(max_length=100, verbose_name='Предварительный просмотр поста')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание поста')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания поста')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления поста')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликовано')], default='draft', max_length=10, verbose_name='Статус')),
                ('hits', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('comments', models.IntegerField(default=0, verbose_name='Количество комментариев')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_posts', to='blog.author', verbose_name='Автор поста')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_category', to='blog.category', verbose_name='Категория')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'db_table': 'posts',
                'ordering': ('-date_published',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата первого посещения сайта')),
                ('ip', models.CharField(db_index=True, editable=False, max_length=40, verbose_name='IP')),
                ('session', models.CharField(db_index=True, editable=False, max_length=40, verbose_name='Сессия')),
                ('user_agent', models.CharField(editable=False, max_length=255, verbose_name='Браузер')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_publications', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'посетителя',
                'verbose_name_plural': 'Посетители',
                'db_table': 'visitors',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Коментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения комментария')),
                ('moderation', models.BooleanField(default=True, verbose_name='Модерация')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_comments', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'коментарий',
                'verbose_name_plural': 'коментарии',
                'db_table': 'comments',
                'ordering': ('created',),
            },
        ),
    ]
