# Generated by Django 3.1.4 on 2020-12-03 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='date_published', verbose_name='URL')),
                ('body', models.TextField(verbose_name='Содержание поста')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания поста')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления поста')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликовано')], default='draft', max_length=10, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'db_table': 'posts',
                'ordering': ('-date_published',),
            },
        ),
    ]
