# Generated by Django 3.1.4 on 2020-12-22 08:59

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок страницы')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание страницы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Cтраницу о блоге',
                'verbose_name_plural': 'Cтраница о блоге',
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, max_length=250, unique='category')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
            },
            managers=[
                ('category_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок страницы')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание страницы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Cтраницу контактов',
                'verbose_name_plural': 'Cтраница контактов',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='date_published')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание поста')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания поста')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления поста')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликовано')], default='draft', max_length=10, verbose_name='Статус')),
                ('hits', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_category', to='publications.category', verbose_name='Категория')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'db_table': 'posts',
                'ordering': ('-date_published',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата первого посещения сайта')),
                ('ip', models.CharField(db_index=True, editable=False, max_length=40, verbose_name='IP')),
                ('session', models.CharField(db_index=True, editable=False, max_length=40, verbose_name='Сессия')),
                ('user_agent', models.CharField(editable=False, max_length=255, verbose_name='Браузер')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_publications', to='publications.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'посетителя',
                'verbose_name_plural': 'Посетители',
                'db_table': 'visitor',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Коментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения комментария')),
                ('moderation', models.BooleanField(default=True, verbose_name='Модерация')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_comments', to='publications.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'db_table': 'comments',
                'ordering': ('created',),
            },
        ),
    ]
