# Generated by Django 3.1.4 on 2020-12-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='status_post',
        ),
    ]
