# Generated by Django 3.1.4 on 2020-12-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20201206_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
