# Generated by Django 3.1.4 on 2020-12-10 12:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20201208_1851'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('category_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
