# Generated by Django 3.1.4 on 2020-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20201210_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(blank=True, max_length=250, unique='about')),
                ('body', models.TextField(verbose_name='Содержание страницы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'страница о блоге',
                'db_table': 'about',
            },
        ),
    ]
