# Generated by Django 3.1.4 on 2020-12-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок страницы')),
                ('body', models.TextField(verbose_name='Содержание страницы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Cтраницу контактов',
                'verbose_name_plural': 'Cтраница контактов',
                'db_table': 'contact',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Cтраницу о блоге', 'verbose_name_plural': 'Cтраница о блоге'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='slug',
        ),
    ]
