# Generated by Django 3.1.4 on 2020-12-19 19:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_auto_20201218_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='about',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание страницы'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание страницы'),
        ),
    ]
