# Generated by Django 3.1.4 on 2020-12-20 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0015_auto_20201219_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='number_of_views',
            new_name='hits',
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата первого посещения сайта')),
                ('ip', models.CharField(db_index=True, editable=False, max_length=40, verbose_name='IP')),
                ('session', models.CharField(db_index=True, editable=False, max_length=40, verbose_name='Сессия')),
                ('user_agent', models.CharField(editable=False, max_length=255, verbose_name='Браузер')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'hit',
                'verbose_name_plural': 'hits',
                'db_table': 'visitor',
                'ordering': ('-created',),
            },
        ),
    ]
