# Generated by Django 3.1.4 on 2020-12-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_remove_visitor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='post',
            new_name='post_id',
        ),
    ]
