# Generated by Django 3.1.4 on 2020-12-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_auto_20201221_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='post_id',
            new_name='post',
        ),
    ]
