# Generated by Django 3.1.4 on 2021-01-15 13:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок страницы')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание страницы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Cтраницу о блоге',
                'verbose_name_plural': 'Cтраница о блоге',
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок страницы')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание страницы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Cтраницу контактов',
                'verbose_name_plural': 'Cтраница контактов',
                'db_table': 'contact',
            },
        ),
    ]
